site_name: bulletin-py
site_description: Documentation for bulletin-py
site_url: https://diegoglezsu.github.io/bulletin-py/
repo_url: https://github.com/diegoglezsu/bulletin-py
repo_name: diegoglezsu/bulletin-py

theme:
  name: material
  palette:
    - scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
      - bulletin.doue: api/doue.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
